name: Release latest

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write

jobs:
  # Push to latest
  container-push-latest:
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: dynamic-buildkite-template
      tag: latest
      dockerfile_path: Dockerfile
      platforms: linux/amd64,linux/arm64
